model_ouput_dir: "./result_models"
log_interval: 1
wandb: False
agent:
  name: "FixedAction"
  # Number of episodes 
  num_episodes: 100
  # Fixed Action Index
  fixed_action_idx: 0
    
env:
  # Sinergym environment name
  name: Eplus-5Zone-hot-discrete-train-v1
  # Reward Type
  reward_type: "Linear"
  # Whether to normalise observations
  normalize: True
  # The observation variables to use for training, offset by 4 to account for time vars 
  obs_to_keep: [4, 5, 13]