model_output_dir: "./result_models"
wandb: True
agent:
  name: "FixedAction_MaxComfort"
  # Number of episodes 
  num_episodes: 5
  # Fixed Action Index
  fixed_action_idx: 9
  # Number of episodes before logging
  log_interval: 1
    
env:
  # Sinergym environment name
  name: Eplus-5Zone-hot-discrete-train-v1
  # Reward Type
  reward_type: "Linear"
  # Whether to normalise observations
  normalize: True
  # The observation variables to use for training, offset by 4 to account for time vars 
  obs_to_keep: [4, 5, 13]