agent:
  # Number of episodes 
  num_episodes: 1460
  # Maximum number of time steps in each episode
  horizon: 24
  # Discount factor
  gamma: 0.99
  # Number of tiles for tile coding
  num_tiles: 20
  # Initial value for Epsilon
  initial_epsilon: 1
  # Annealing rate for Epsilon
  epsilon_annealing: 0.999
  # Initial learning rate
  learning_rate: 0.1
  # Annealing rate for learning rate
  learning_rate_annealing: 0.999
    
env:
  # Sinergym environment name
  name: Eplus-5Zone-hot-discrete-v1
  # Whether to normalise observations
  normalize: True
  # The observation variables to use for training, offset by 4 to account for time vars 
  obs_to_keep: [0, 1, 8, 10]
  # The type of each observation variable: 
  #   0 - slowly-changing continuous var
  #   1 - fast-changing continuous var
  #   2 - discrete var
  mask: [0, 0, 0, 0]
