agent:
  # script to run inside experiment container
  origin: ./train_beobench.py
  # configuration that can be accessed by script above
  config:
    num_episodes: 1460
    horizon: 24
    gamma: 0.99
    step_size: 0.05
    initial_epsilon: 1
    epsilon_annealing: 0.999
    learning_rate: 0.1
    learning_rate_annealing: 0.999
env:
  # gym framework from which we want use an environment
  gym: ./beobench_env
  # gym-specific environment configuration
  config:
    # sinergym environment name
    name: Eplus-5Zone-hot-discrete-v1
    # whether to normalise observations
    normalize: True
wrappers: [] # no wrappers added for this example
general:
  # save experiment data to ``./beobench_results`` directory
  local_dir: ./beobench_results
