agent:
  initial_epsilon: 1
  epsilon_annealing: 0.999
  learning_rate: 0.1
  learning_rate_annealing: 0.999
  gamma: 0.99
env:
  name: Eplus-5Zone-hot-discrete-v1
  # whether to normalise observations
  masks:
  normalize: True
training:
  num_episodes: 14600
  horizon: 24