agent:
  # script to run inside experiment container
  origin: ./agent_mbrl.py
  # configuration that can be accessed by script above
  config:
    num_episodes: 200

hyperparams:
  eps_annealing: 0.999
  lr_annealing: 0.999
  horizon: 10000

env:
  # gym framework from which we want use an environment
  gym: sinergym
  # gym-specific environment configuration
  config:
    # sinergym environment name
    name: Eplus-5Zone-mixed-discrete-v1
    # whether to normalise observations
    normalize: True
wrappers: [] # no wrappers added for this example
general:
  # save experiment data to ``./beobench_results`` directory
  local_dir: ./beobench_results